type CommandResponse {
  "Response code"
  code: Int
  "Response message"
  message: String
}

type LotteryGameSheetConfig {
  "Sheet config ID"
  _id: ID!
  "Draw consecutive"
  validFromDraw: Int
  "Draw consecutive"
  validUntilDraw: Int
  "Tickets per sheet"
  ticketsPerSheet: Int
  "Tickets per price"
  ticketPrice: Int
  "Lottery id"
  lotteryId: String
  "game id"
  gameId: String
  "Config sheet approved"
  approved: String
  "Config sheet approved"
  approvedNotes: String
  "Config sheet approved"
  approvedUsername: String
  "Approved timestamp"
  approvedTimestamp: BigInt
  "Config sheet revoked"
  revoked: Boolean
  "Config sheet revoked notes"
  revokedNotes: String
  "Config sheet revoked timestamp"
  revokedTimestamp: BigInt
  "Config sheet revoked user name"
  revokedUsername: String
  "Config sheet version"
  version: Int
  "Creation timestamp"
  creationTimestamp: BigInt
  "Creator username"
  creationUsername: String
  "Creator user id"
  creationUserId: String
  "Modification timestamp"
  editionTimestamp: BigInt
  "Modifier user id"
  editionUserId: String
  "Modifier username"
  editionUsername: String
}

input LotteryGameSheetConfigFilterInput {
  "Name"
  name: String
  "Sheet config version"
  sheetConfigVersion: String
  "Lottery id"
  lotteryId: String
  "game id"
  gameId: String
}

input LotteryGameConfigSheetInput {
  "Draw consecutive"
  validFromDraw: Int
  "Draw consecutive"
  validUntilDraw: Int
  "Tickets per sheet"
  ticketsPerSheet: Int
  "Tickets per price"
  ticketPrice: Int
  "Lottery Id"
  lotteryId: String
  "game id"
  gameId: String
}

type Query {
  "Get sheet configs filtered "
  LotteryGameSheetConfigList(
    filterInput: LotteryGameSheetConfigFilterInput!
  ): [LotteryGameSheetConfig]

  "Get Game by its id"
  LotteryGameSheetConfig(
    id: String
    filterInput: LotteryGameSheetConfigFilterInput
  ): LotteryGameSheetConfig
}

type Mutation {
  "Create a new Game"
  CreateLotteryGameSheetConfig(
    input: LotteryGameConfigSheetInput!
  ): CommandResponse
  "Update the sheet config"
  UpdateLotteryGameSheetConfig(
    id: ID!
    input: LotteryGameConfigSheetInput!
  ): CommandResponse
  "Approve the sheet config"
  ApproveLotteryGameSheetConfig(
    id: ID!
    approved: String
    approvedNotes: String
  ): CommandResponse
  "Revoke the sheet config"
  RevokeLotteryGameSheetConfig(
    id: ID!
    revoked: Boolean
    revokedNotes: String
  ): CommandResponse
}

type Subscription {
  "This events is triggered when a Game is created or updated"
  LotteryGameSheetConfigUpdatedSubscription(gameId: String): LotteryGameSheetConfig
}
